synclient TapButton1=0 \
          TapButton2=0 \
          TapButton3=0 \
          ClickFinger1=1 \
          ClickFinger2=3 \
          ClickFinger3=2 \
          VertTwoFingerScroll=1 \
          HorizTwoFingerScroll=1 \
          VertEdgeScroll=0 \
          HorizEdgeScroll=0 \
          RTCornerButton=0 \
          RBCornerButton=0 \
          LTCornerButton=0 \
          LBCornerButton=0 &

exec i3
